name: 🚀 Request a feature
description: RFC and ideas for new features and improvements
type: Feature
labels: [feature]
body:
    - type: textarea
      id: description
      attributes:
          label: Description
          description: Please describe the new feature and provide as many details as possible (e.g. code samples or screenshots).
      validations:
          required: true
