services:
    contao.listener.initialize_application:
        class: Contao\InstallationBundle\EventListener\InitializeApplicationListener
        calls:
            - [setContainer, ['@service_container']]
        tags:
            - kernel.event_listener
