name: Isolated tests

on:
    workflow_dispatch: ~
    schedule:
        - cron: 0 13 * * MON,THU

permissions: read-all

defaults:
    run:
        # Simulate an interactive terminal with color support
        shell: script -q -e -c "export TERM=xterm; bash {0}"

jobs:
    tests:
        name: Isolated tests
        runs-on: ubuntu-latest
        steps:
            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: 8.3 # latest stable version
                  extensions: dom, fileinfo, filter, gd, hash, intl, json, mbstring, mysqli, pcre, pdo_mysql, zlib
                  coverage: none

            - name: Checkout
              uses: actions/checkout@v4
              with:
                  show-progress: false

            - name: Install Contao
              uses: ramsey/composer-install@v3

            - name: Install the isolated tests
              uses: ramsey/composer-install@v3
              with:
                  working-directory: vendor-bin/isolated-tests

            - name: Run the unit tests
              run: vendor/bin/phpunit --extension Contao\\CoreBundle\\Tests\\PhpunitExtension\\GlobalStateWatcher

            - name: Run the unit tests isolated
              run: vendor-bin/isolated-tests/bin/run-tests-isolated
